# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: master
    - run: flutter pub get
    - name: 获取版本号
      if: ${{ matrix.type != 'windows' }}
      run: |
        echo "version=$(awk -F': ' '/version:/ {gsub("\\+", "-", $2); print $2}' pubspec.yaml)" >> "$GITHUB_ENV"
    - name: 打印版本号
      run: |
        echo "version: ${{ env.version }}"
    - name: Build Web
      run: flutter build web --web-renderer canvaskit --no-web-resources-cdn
    - name: zipped build
      run: |
        tar -czvf releaseWeb.tar.gz -C  build/web
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        tag: "v${{ env.version }}"
        draft: false
        artifacts: "*.tar.gz"
        allowUpdates: true
        token: ${{ github.token }}

