# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: master
    - run: flutter pub get
    - name: Build Web
      run: flutter build web --web-renderer canvaskit --no-web-resources-cdn
    - name: zipped build
      run: |
          Compress-Archive -Path 'build/web' -DestinationPath 'realeaseWeb.zip'
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        tag: "v${{ env.version }}"
        draft: false
        artifacts: "*.zip"
        allowUpdates: true
        token: ${{ github.token }}

